{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import random\n",
    "\n",
    "#premier_tirage(), une fonction qui permet de\n",
    "#faire un tirage aléatoire sans remise dans le deck\n",
    "\n",
    "def premier_tirage(deck):\n",
    "    tirage = random.sample(deck, 5)\n",
    "    for i in tirage:\n",
    "        deck.remove(i)\n",
    "    return tirage, deck\n",
    "\n",
    "#choix_carte(), une fonction qui prend un \n",
    "#tirage en entrée, et permet au joueur \n",
    "#de choisir quelle carte il garde ou non pour le deuxième tirage\n",
    "\n",
    "def choix_carte(chosen_cards):\n",
    "    new_chosen_cards = []\n",
    "    count = 0\n",
    "    for card in chosen_cards:\n",
    "        #if count < 4:\n",
    "        print('Voulez vous garder la carte(y\\n)? : ', card)\n",
    "        user_answer = input()\n",
    "        if user_answer =='y':\n",
    "            #count +* 1\n",
    "            new_chosen_cards.append(card)\n",
    "    return new_chosen_cards\n",
    "\n",
    "#deuxieme_tirage(), qui permet,\n",
    "#à partir du jeu obtenu avec la fonction choix_carte \n",
    "#et le deck obtenu avec la fonction premier tirage, \n",
    "#de constituer le tirage final du joueur\n",
    "\n",
    "def deuxieme_tirage(jeu, deck):\n",
    "    nb_carte = len(jeu)\n",
    "    carte_a_tirer = 5 - nb_carte\n",
    "    nouvelle_carte = random.sample(deck, carte_a_tirer)\n",
    "    for i in nouvelle_carte:\n",
    "        jeu.append(i)\n",
    "    return jeu\n",
    "\n",
    "\n",
    "#machine(), une fonction qui fait le premier tirage,\n",
    "#l'affiche, propose au joueur les cartes afin de\n",
    "#choisir celles à garder, puis fait le deuxième \n",
    "#tirage et l'affiche et le retourne\n",
    "\n",
    "\n",
    "def machine():\n",
    "    deck = ['2-h','3-h','4-h','5-h','6-h','7-h','8-h','9-h','10-h','J-h','Q-h','K-h','A-h','2-d','3-d','4-d','5-d','6-d','7-d','8-d','9-d','10-d','J-d','Q-d','K-d','A-d','2-c','3-c','4-c','5-c','6-c','7-c','8-c','9-c','10-c','J-c','Q-c','K-c','A-c','2-s','3-s','4-s','5-s','6-s','7-s','8-s','9-s','10-s','J-s','Q-s','K-s','A-s']\n",
    "    tirage1, deck = premier_tirage(deck)\n",
    "    print(tirage1)\n",
    "    jeu = choix_carte(tirage1)\n",
    "    tirage_final = deuxieme_tirage(jeu, deck)\n",
    "    print(tirage_final)\n",
    "    return tirage_final\n",
    "def decompose_jeu(tirage):\n",
    "    dic = {}\n",
    "    keys = [1,2,3,4,5]\n",
    "    valeur = []\n",
    "    couleur = []\n",
    "    for i,k in zip(tirage,keys):\n",
    "        dic[k] = i.split('-')\n",
    "    for key in dic.keys():\n",
    "        valeur.append(dic[key][0])\n",
    "        couleur.append(dic[key][1])\n",
    "    return valeur, couleur\n",
    "def convert_carte(liste):\n",
    "    for e,i in zip(liste, range(0,5)):\n",
    "        try:\n",
    "            liste[i] = int(e)\n",
    "        except:\n",
    "            if e == 'J':\n",
    "                liste[i] = 11\n",
    "            elif e == 'Q':\n",
    "                liste[i] = 12\n",
    "            elif e == 'K':\n",
    "                liste[i] = 13\n",
    "            elif e == 'A':\n",
    "                liste[i] = 1\n",
    "            else:\n",
    "                continue\n",
    "    return liste\n",
    "def quinte_flush_royale(tirage):\n",
    "    valeur_gagnante = ['10','J','Q','K','A']\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    if sorted(valeur_gagnante) == sorted(valeur) and couleur.count(couleur[0]) == 5:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "def quinte_flush(tirage):\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    valeur = convert_carte(valeur)\n",
    "    valeur = sorted(valeur)\n",
    "    suite = []\n",
    "    for e, i in zip(valeur[0:-1], range(len(valeur)-1)):\n",
    "        if e+1 == valeur[i+1]:\n",
    "            suite.append('True')\n",
    "    if suite.count('True') == 4 and couleur.count(couleur[0]) == 5:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "def carre(tirage):\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    valeur1 = pd.Series(valeur)\n",
    "    uniques = valeur1.unique()\n",
    "    count = []\n",
    "    for i in uniques:\n",
    "        count.append(valeur.count(i))\n",
    "    if len(uniques) == 2 and sorted(count) == [1,4]:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "def full(tirage):\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    valeur1 = pd.Series(valeur)\n",
    "    uniques = valeur1.unique()\n",
    "    count = []\n",
    "    for i in uniques:\n",
    "        count.append(valeur.count(i))\n",
    "    if len(uniques) == 2 and sorted(count) == [2,3]:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "def flush(tirage):\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    if couleur.count(couleur[0])  == 5:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "    \n",
    "def quinte(tirage):\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    valeur = convert_carte(valeur)\n",
    "    valeur = sorted(valeur)\n",
    "    suite = []\n",
    "    for e, i in zip(valeur[0:-1], range(len(valeur)-1)):\n",
    "        if e+1 == valeur[i+1]:\n",
    "            suite.append('True')\n",
    "    if suite.count('True') == 4 or valeur == [1, 10, 11, 12, 13,]:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "def brelan(tirage):\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    valeur1 = pd.Series(valeur)\n",
    "    uniques = valeur1.unique()\n",
    "    count = []\n",
    "    for i in uniques:\n",
    "        count.append(valeur.count(i))\n",
    "    if len(uniques) == 3 and sorted(count) == [1, 1, 3]:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "def double_paire(tirage):\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    valeur1 = pd.Series(valeur)\n",
    "    uniques = valeur1.unique()\n",
    "    count = []\n",
    "    for i in uniques:\n",
    "        count.append(valeur.count(i))\n",
    "    if len(uniques) == 3 and sorted(count) == [1, 2, 2]:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "def paire(tirage):\n",
    "    valeur, couleur = decompose_jeu(tirage)\n",
    "    valeur1 = pd.Series(valeur)\n",
    "    uniques = valeur1.unique()\n",
    "    count = []\n",
    "    for i in uniques:\n",
    "        count.append(valeur.count(i))\n",
    "    if len(uniques) == 4 and sorted(count) == [1, 1, 1, 2]:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "    \n",
    "#gain(), une fonction permettant de calculer \n",
    "#les gains et d'afficher le résultat au joueur.\n",
    "    \n",
    "def gain(tirage_final, mise):\n",
    "    if quinte_flush_royale(tirage_final) == True:\n",
    "        g = mise*250\n",
    "        resultat = \"Quinte Flush Royale !! Vous gagnez \" + str(g) + \"euros ! Félicitaions!!\"\n",
    "        return g, resultat\n",
    "    elif quinte_flush(tirage_final) == True:\n",
    "        g = mise*50\n",
    "        resultat = \"Quinte Flush !! Vous gagnez\" + str(g) + \"euros ! Félicitations !!\"\n",
    "        return g, resultat\n",
    "    elif carre(tirage_final) == True:\n",
    "        g = mise*25\n",
    "        resultat = \"Carré !! Vous gagnez\" + str(g) + \"euros ! Félicitations !!\"\n",
    "        return g, resultat\n",
    "    elif full(tirage_final) == True:\n",
    "        g = mise*9\n",
    "        resultat = \"Full ! Vous gagnez\" + str(g) + \"euros ! Félicitations !\"\n",
    "        return g, resultat\n",
    "    elif flush(tirage_final) == True:\n",
    "        g = mise*6\n",
    "        resultat = \"Flush ! Vous gagnez\" + str(g) + \"euros ! Félicitations !\"\n",
    "        return g, resultat\n",
    "    elif quinte(tirage_final) == True:\n",
    "        g = mise*4\n",
    "        resultat = \"Quinte ! Vous gagnez\" + str(g) + \"euros ! Félicitations !\"\n",
    "        return g, resultat\n",
    "    elif brelan(tirage_final) == True:\n",
    "        g = mise*3\n",
    "        resultat = \"Brelan ! Vous gagnez\" + str(g) + \"euros ! Félicitations !\"\n",
    "        return g, resultat\n",
    "    elif double_paire(tirage_final) == True:\n",
    "        g = mise*2\n",
    "        resultat = \"Double paire !! Vous gagnez\" + str(g) + \"euros ! Félicitations !\"\n",
    "        return g, resultat\n",
    "    elif paire(tirage_final) == True:\n",
    "        g = mise*1\n",
    "        resultat = \"Paire ! Vous gagnez\" + str(g) + \"euros ! Félicitations !\"\n",
    "        return g, resultat\n",
    "    else:\n",
    "        g = 0\n",
    "        resultat = \"Perdu ! Rentre chez toi et cherche un vrai boulot\"\n",
    "        return g, resultat\n",
    "    \n",
    "#partie(), une fonction qui prend en entrée\n",
    "#une mise et une bankroll (total de l'argent\n",
    "#disponible pour jouer), perment de faire le tirage, \n",
    "#et calcule la nouvelle bankroll en fonction des gains\n",
    "    \n",
    "def partie(mise, bankroll):\n",
    "    main = machine()\n",
    "    g, resultat = gain(main, mise)\n",
    "    bankroll = bankroll - mise\n",
    "    bankroll += g\n",
    "    return resultat, bankroll\n",
    "\n",
    "\n",
    "#video_poker(), une fonction qui permet au joueur \"d'inserer de l'argent\" (bankroll),\n",
    "#de choisir la mise puis de jouer jusqu'a \n",
    "#avoir tout perdu (ou pas si il a de la chance!)\n",
    "\n",
    "def video_poker():\n",
    "    bankroll = int(input(\"BANQUE\"))\n",
    "    mise_joueur = int(input(\"VOTRE JEU: \"))\n",
    "    \n",
    "    while bankroll - mise_joueur >= 0:\n",
    "        resultat, bankroll = partie(mise_joueur, bankroll)\n",
    "        print(resultat)\n",
    "        print(\"BANQUE: \" + str(bankroll))\n",
    "        if bankroll == 0:\n",
    "            print(\"U LOOSE\")\n",
    "            break\n",
    "        else:\n",
    "            mise_joueur = int(input(\"VOTRE JEU:\"))\n",
    "            if bankroll - mise_joueur < 0:\n",
    "                print(\"MISE TROP HAUTE\")\n",
    "                mise_joueur = int(input(\"VOTRE JEU: \"))\n",
    "video_poker()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
